import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit'
import { RootState, AppThunk } from '../../app/store'
import { fetchCount } from './counterAPI'

export interface CounterState {
	value: number
	maxId: number
	selectedQ: Object
	status: 'idle' | 'loading' | 'failed'
	questionList: Array<Object>
}

const initialState: CounterState = {
	value: 0,
	status: 'idle',
	questionList: [],
	maxId: 1,
	selectedQ: {},
}

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const incrementAsync = createAsyncThunk(
	'counter/fetchCount',
	async (amount: number) => {
		const response = await fetchCount(amount)
		// The value we return becomes the `fulfilled` action payload
		return response.data
	}
)

export const counterSlice = createSlice({
	name: 'counter',
	initialState,
	// The `reducers` field lets us define reducers and generate associated actions
	reducers: {
		increment: (state) => {
			state.value += 1
		},
		selectQuestion: (state, action: PayloadAction<number>) => {
			state.value -= 1
			state.selectedQ = state.questionList[action.payload - 1]
		},
		// Use the PayloadAction type to declare the contents of `action.payload`
		incrementByAmount: (state, action: PayloadAction<Object>) => {
			state.questionList.push({ ...action.payload })
			state.maxId += 1
		},
	},
	// The `extraReducers` field lets the slice handle actions defined elsewhere,
	// including actions generated by createAsyncThunk or in other slices.
	extraReducers: (builder) => {
		builder
			.addCase(incrementAsync.pending, (state) => {
				state.status = 'loading'
			})
			.addCase(incrementAsync.fulfilled, (state, action) => {
				state.status = 'idle'
				state.questionList = action.payload
				state.maxId = action.payload.length
			})
	},
})

export const { increment, selectQuestion, incrementByAmount } =
	counterSlice.actions

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectQuestionList = (state: RootState) =>
	state.counter.questionList

export const selectedQuestion = (state: RootState) => state.counter.selectedQ

export const questionMaxId = (state: RootState) => state.counter.maxId
export default counterSlice.reducer
